# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Deploy tags on PyPI
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: parsys-python
  password:
    secure: CrM7uSAZ92wkAon9AhjgUEpLHez4Gxc/WFP4ICeoyLVuv/6TSULfS0qMAVz5353GsPwkUt3Etu1eK1VKbWln6JZJA7utFfgdO40JG4SQGF7Lib0CSPAppTsujQ5WWF78aOP9/N3t5ia7PlplD/JqPyXyftq2FNzuHfdj3WEjs4ThCPx05HI8yLT+M8qsJLU2V1dTUEPrkSrgC1sstvnDTpPVHRekAHTlAzGYvVJB4TNH/rtbs92R4VbZS3P3S9p8FKa23umqyxIVsikCPCk9WoCV6qVmDP4PZS7Il2HUjZnhM7+0ejhIQs8j8iqLOhbay7Q8bWcVrTHM9idjtbQ+7Eoa11YZLWo2lDrmWzNPlnM4A1Q26+37vedHohkkkgH2ivDae8PloxPxFce7XtzM3L4LFTDiuFosxal6nOhz8RXjl46Ic/8fgUXh5J5a7y0ax/bChVijLFc2Cs2bRoogXgBfoinGTB2rOySQVMlHAIlmdBcdk5GuVUch605aiImvwg/0H0V7VPVGt1ORM9dl0I/mq4uwtj7V5XTVYdBctvrwFzc0jNBvTSpIiJgyQfYUmgpYZW+5xjESKhjmrolzUXOaHe6mdZdjVAJriMZMzxCFLKxe8aEHKUbjRBVB81C6sIk5LL7R1eiIyJaOHYj7cw5xOCLlQHnFawwqiB/OzCI=
  on:
    tags: true
    repo: mozilla-iam/iam-profile-faker
    python: 3.6
