---
apiVersion: v1
kind: Service
metadata:
  name: iam-profile-faker-service
  namespace: dino-park
spec:
  selector:
    app: iam-profile-faker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
